// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrueCentralVms.Server.Data;

#nullable disable

namespace TrueCentralVms.Server.Migrations
{
    [DbContext(typeof(VmsDbContext))]
    [Migration("20260909220050_AccessFaces")]
    partial class AccessFaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("AccessCards");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("SupportsCards")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsEvents")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsFace")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsFingerprint")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsRemoteControl")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("AccessDevices");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessDoor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessDeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("NameFromDevice")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StateReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessDeviceId", "Number")
                        .IsUnique();

                    b.ToTable("AccessDoors");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessDeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Credential")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DoorName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("DoorNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("MajorType")
                        .HasColumnType("integer");

                    b.Property<int?>("MinorType")
                        .HasColumnType("integer");

                    b.Property<string>("PersonName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AccessDeviceId", "Timestamp");

                    b.ToTable("AccessEvents");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessFace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<int>("Bytes")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ImageCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId")
                        .IsUnique();

                    b.ToTable("AccessFaces");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessFingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("TemplateCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId", "Number")
                        .IsUnique();

                    b.ToTable("AccessFingerprints");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessScheduleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccessLevels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevelDoor", b =>
                {
                    b.Property<int>("AccessLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("AccessDoorId")
                        .HasColumnType("integer");

                    b.HasKey("AccessLevelId", "AccessDoorId");

                    b.HasIndex("AccessDoorId");

                    b.ToTable("AccessLevelDoors");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevelPerson", b =>
                {
                    b.Property<int>("AccessLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccessLevelId", "AccessPersonId");

                    b.HasIndex("AccessPersonId");

                    b.ToTable("AccessLevelPersons");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("PinCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Position")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SyncError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("AccessPersons");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessPersonDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessDeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("AccessPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("AppliedHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("PendingRemoval")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessDeviceId");

                    b.HasIndex("AccessPersonId", "AccessDeviceId")
                        .IsUnique();

                    b.ToTable("AccessPersonDevices");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessPlanSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("SegmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("AccessPlanSlots");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PlanNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccessSchedules");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessScheduleSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("EndMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessScheduleId", "Day");

                    b.ToTable("AccessScheduleSegments");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmPanelId")
                        .HasColumnType("integer");

                    b.Property<string>("ArmState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("InAlarm")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlarmPanelId", "Number")
                        .IsUnique();

                    b.ToTable("AlarmAreas");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlarmPanelId")
                        .HasColumnType("integer");

                    b.Property<string>("AreaName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("AreaNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Operator")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PanelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ZoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("AlarmPanelId", "ReceivedAt");

                    b.HasIndex("Kind", "ReceivedAt");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcLoss")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GatewayDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("PanelTamper")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("AlarmPanels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmPanelId")
                        .HasColumnType("integer");

                    b.Property<int?>("AreaNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Armed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bypassed")
                        .HasColumnType("boolean");

                    b.Property<string>("DetectorType")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<bool>("InAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowBattery")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("Signal")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Tamper")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZoneType")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmPanelId", "Number")
                        .IsUnique();

                    b.ToTable("AlarmZones");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Username", "Timestamp");

                    b.HasIndex("Category", "Action", "Timestamp");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RtspChannel")
                        .HasColumnType("integer");

                    b.Property<string>("RtspMainUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RtspSubUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("SupportsPtz")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseFfmpegProxy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ChannelNumber")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Decoder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("Decoders");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnprEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RtspPort")
                        .HasColumnType("integer");

                    b.Property<int>("SdkPort")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Host", "SdkPort")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.PlateEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CharConfidences")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<string>("DetectionMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Direction")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer");

                    b.Property<string>("PlateColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("PlateHeight")
                        .HasColumnType("double precision");

                    b.Property<string>("PlateImagePath")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("PlateType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("PlateWidth")
                        .HasColumnType("double precision");

                    b.Property<double>("PlateX")
                        .HasColumnType("double precision");

                    b.Property<double>("PlateY")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SceneImagePath")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("SpeedKmh")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleAttributes")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("VehicleLengthCm")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Violation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("DeviceId", "ReceivedAt");

                    b.ToTable("PlateEvents");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.ScreenWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedChannelId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedStreamType")
                        .HasColumnType("integer");

                    b.Property<int>("DecodeChannel")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SpanCols")
                        .HasColumnType("integer");

                    b.Property<int>("SpanRows")
                        .HasColumnType("integer");

                    b.Property<int>("WallScreenId")
                        .HasColumnType("integer");

                    b.Property<int>("WindowIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedChannelId");

                    b.HasIndex("WallScreenId", "WindowIndex")
                        .IsUnique();

                    b.ToTable("ScreenWindows");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.SmtpSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowInvalidCertificate")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("PasswordCiphertext")
                        .HasColumnType("bytea");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Security")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("SmtpSettings");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("SupportsLibrary")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsLiveAudio")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTts")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.StreamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MtxSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("RtspChannel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.HasIndex("MtxSessionId");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.VideoWall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<int>("DecoderId")
                        .HasColumnType("integer");

                    b.Property<int?>("FullscreenWindowId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecoderId");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallFloatingWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedChannelId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedStreamType")
                        .HasColumnType("integer");

                    b.Property<int>("DecodeChannel")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("H")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeH")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeW")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeX")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeY")
                        .HasColumnType("double precision");

                    b.Property<int>("VideoWallId")
                        .HasColumnType("integer");

                    b.Property<double>("W")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AssignedChannelId");

                    b.HasIndex("VideoWallId");

                    b.ToTable("WallFloatingWindows");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("SpanCols")
                        .HasColumnType("integer");

                    b.Property<int>("SpanRows")
                        .HasColumnType("integer");

                    b.Property<int>("StreamType")
                        .HasColumnType("integer");

                    b.Property<int>("WallLayoutPresetId")
                        .HasColumnType("integer");

                    b.Property<int>("WindowIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("WallLayoutPresetId");

                    b.ToTable("WallLayoutItems", (string)null);
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("VideoWallId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoWallId", "Name")
                        .IsUnique();

                    b.ToTable("WallLayouts");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("WallLayoutPresetId")
                        .HasColumnType("integer");

                    b.Property<int>("WindowMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WallLayoutPresetId");

                    b.ToTable("WallLayoutScreens", (string)null);
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayChannel")
                        .HasColumnType("integer");

                    b.Property<int?>("FullscreenWindowId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("VideoWallId")
                        .HasColumnType("integer");

                    b.Property<int>("WindowMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoWallId", "Row", "Col")
                        .IsUnique();

                    b.ToTable("WallScreens");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionsJson")
                        .HasColumnType("text");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("RunCount")
                        .HasColumnType("bigint");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TriggerType", "Enabled");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WorkflowAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("boolean");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SecretCiphertext")
                        .HasColumnType("bytea");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Order");

                    b.ToTable("WorkflowActions");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WorkflowAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AcknowledgedFrom")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("AcknowledgedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChannelIdsJson")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImagePathsJson")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresAck")
                        .HasColumnType("boolean");

                    b.Property<long?>("RunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Sound")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SoundRepeat")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TriggerSummary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAt");

                    b.HasIndex("AcknowledgedAt", "RaisedAt");

                    b.ToTable("WorkflowAlerts");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WorkflowRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TriggerJson")
                        .HasColumnType("text");

                    b.Property<string>("TriggerSummary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("WorkflowId", "StartedAt");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessCard", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessPerson", "AccessPerson")
                        .WithMany("Cards")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessDoor", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessDevice", "AccessDevice")
                        .WithMany("Doors")
                        .HasForeignKey("AccessDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessDevice");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessEvent", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessDevice", "AccessDevice")
                        .WithMany()
                        .HasForeignKey("AccessDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessDevice");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessFace", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessPerson", "AccessPerson")
                        .WithOne("Face")
                        .HasForeignKey("TrueCentralVms.Server.Data.Entities.AccessFace", "AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessFingerprint", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessPerson", "AccessPerson")
                        .WithMany("Fingerprints")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevel", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessSchedule", "AccessSchedule")
                        .WithMany("Levels")
                        .HasForeignKey("AccessScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessSchedule");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevelDoor", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessDoor", "AccessDoor")
                        .WithMany("Levels")
                        .HasForeignKey("AccessDoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessLevel", "AccessLevel")
                        .WithMany("Doors")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessDoor");

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevelPerson", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessLevel", "AccessLevel")
                        .WithMany("Persons")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessPerson", "AccessPerson")
                        .WithMany("Levels")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessPersonDevice", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessDevice", "AccessDevice")
                        .WithMany()
                        .HasForeignKey("AccessDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessPerson", "AccessPerson")
                        .WithMany("Devices")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessDevice");

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessScheduleSegment", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AccessSchedule", "AccessSchedule")
                        .WithMany("Segments")
                        .HasForeignKey("AccessScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessSchedule");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmArea", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AlarmPanel", "AlarmPanel")
                        .WithMany("Areas")
                        .HasForeignKey("AlarmPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmPanel");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmZone", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.AlarmPanel", "AlarmPanel")
                        .WithMany("Zones")
                        .HasForeignKey("AlarmPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmPanel");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Channel", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Device", "Device")
                        .WithMany("Channels")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.PasswordHistory", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.User", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.PlateEvent", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.ScreenWindow", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Channel", "AssignedChannel")
                        .WithMany()
                        .HasForeignKey("AssignedChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueCentralVms.Server.Data.Entities.WallScreen", "WallScreen")
                        .WithMany("Windows")
                        .HasForeignKey("WallScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedChannel");

                    b.Navigation("WallScreen");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.VideoWall", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Decoder", "Decoder")
                        .WithMany("Walls")
                        .HasForeignKey("DecoderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Decoder");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallFloatingWindow", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Channel", "AssignedChannel")
                        .WithMany()
                        .HasForeignKey("AssignedChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueCentralVms.Server.Data.Entities.VideoWall", "VideoWall")
                        .WithMany("Floating")
                        .HasForeignKey("VideoWallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedChannel");

                    b.Navigation("VideoWall");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutItem", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueCentralVms.Server.Data.Entities.WallLayoutPreset", "Preset")
                        .WithMany("Items")
                        .HasForeignKey("WallLayoutPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutPreset", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.VideoWall", "VideoWall")
                        .WithMany("Layouts")
                        .HasForeignKey("VideoWallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoWall");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutScreen", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.WallLayoutPreset", "Preset")
                        .WithMany("Screens")
                        .HasForeignKey("WallLayoutPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallScreen", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.VideoWall", "VideoWall")
                        .WithMany("Screens")
                        .HasForeignKey("VideoWallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoWall");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WorkflowAction", b =>
                {
                    b.HasOne("TrueCentralVms.Server.Data.Entities.Workflow", "Workflow")
                        .WithMany("Actions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessDevice", b =>
                {
                    b.Navigation("Doors");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessDoor", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessLevel", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessPerson", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Devices");

                    b.Navigation("Face");

                    b.Navigation("Fingerprints");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AccessSchedule", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.AlarmPanel", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Decoder", b =>
                {
                    b.Navigation("Walls");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Device", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.User", b =>
                {
                    b.Navigation("PasswordHistories");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.VideoWall", b =>
                {
                    b.Navigation("Floating");

                    b.Navigation("Layouts");

                    b.Navigation("Screens");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallLayoutPreset", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Screens");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.WallScreen", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("TrueCentralVms.Server.Data.Entities.Workflow", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
