namespace TrueCentralVms.Server.Services;

/// <summary>
/// Catálogo de categorías y acciones de la bitácora. Las CLAVES son estables
/// (van a la base y a los filtros de la API); las etiquetas en español son
/// solo presentación y las consume el panel vía /api/audit/catalog. Registrar
/// una acción nueva aquí basta para que aparezca en los filtros del panel.
/// </summary>
public static class AuditCatalog
{
    public sealed record ActionInfo(string Key, string Label);
    public sealed record CategoryInfo(string Key, string Label, IReadOnlyList<ActionInfo> Actions);

    public static readonly IReadOnlyList<CategoryInfo> Categories =
    [
        new("auth", "Autenticación",
        [
            new("login", "Inicio de sesión"),
            new("login-failed", "Inicio de sesión rechazado"),
            new("login-blocked", "Login bloqueado (clave vencida)"),
            new("logout", "Cierre de sesión"),
            new("password-changed", "Cambio de contraseña"),
            new("setup-admin", "Creación del primer administrador"),
        ]),
        new("users", "Usuarios",
        [
            new("user-created", "Usuario creado"),
            new("user-updated", "Usuario modificado"),
            new("user-deleted", "Usuario eliminado"),
        ]),
        new("devices", "Dispositivos",
        [
            new("device-created", "Dispositivo agregado"),
            new("device-updated", "Dispositivo modificado"),
            new("device-deleted", "Dispositivo eliminado"),
            new("device-revalidated", "Dispositivo revalidado"),
            new("device-probed", "Prueba de conexión"),
            new("channel-updated", "Canal modificado"),
            new("channels-enabled-bulk", "Canales con señal habilitados en bloque"),
            new("discovery-scan", "Búsqueda de equipos en la red"),
        ]),
        new("live", "Video en vivo",
        [
            new("view-started", "Comenzó a ver un canal"),
            new("view-stopped", "Dejó de ver un canal"),
            new("session-kicked", "Sesión de video expulsada"),
            new("snapshot-web", "Miniatura solicitada desde el panel"),
            new("snapshot-client", "Captura guardada (cliente)"),
            new("clip-started", "Grabación local iniciada (cliente)"),
            new("clip-saved", "Grabación local guardada (cliente)"),
            new("custom-view-saved", "Vista guardada"),
            new("custom-view-updated", "Vista modificada"),
            new("custom-view-deleted", "Vista eliminada"),
            new("custom-view-applied", "Vista cargada en la grilla"),
        ]),
        new("ptz", "Control PTZ",
        [
            new("ptz-moved", "Operó el PTZ"),
            new("ptz-preset-goto", "Fue a un preset"),
            new("ptz-preset-saved", "Guardó un preset"),
            new("ptz-preset-deleted", "Borró un preset"),
        ]),
        new("playback", "Reproducción",
        [
            new("search", "Búsqueda de grabaciones"),
            new("play", "Reproducción de grabación"),
            new("export", "Exportación de grabación (servidor)"),
            new("export-saved", "Exportación guardada (cliente)"),
            new("export-cancelled", "Exportación cancelada (cliente)"),
            new("export-failed", "Exportación fallida (cliente)"),
            new("snapshot-saved", "Captura de reproducción (cliente)"),
            new("clip-saved", "Cápsula de reproducción (cliente)"),
        ]),
        new("wall", "Muro de video",
        [
            new("decoder-created", "Decodificador agregado"),
            new("decoder-updated", "Decodificador modificado"),
            new("decoder-deleted", "Decodificador eliminado"),
            new("decoder-tested", "Decodificador probado"),
            new("wall-created", "Muro creado"),
            new("wall-updated", "Muro modificado"),
            new("wall-deleted", "Muro eliminado"),
            new("wall-synced", "Muro sincronizado"),
            new("window-assigned", "Cámara asignada a ventana"),
            new("external-assigned", "Fuente externa asignada"),
            new("window-cleared", "Ventana limpiada"),
            new("wall-cleared", "Muro limpiado completo"),
            new("windows-swapped", "Ventanas intercambiadas"),
            new("window-mode-changed", "División de monitor cambiada"),
            new("windows-grouped", "Ventanas agrupadas"),
            new("window-ungrouped", "Ventana desagrupada"),
            new("window-subdivided", "Ventana subdividida"),
            new("fullscreen-entered", "Pantalla completa (monitor)"),
            new("fullscreen-exited", "Salió de pantalla completa (monitor)"),
            new("wall-fullscreen-entered", "Pantalla completa (muro)"),
            new("wall-fullscreen-exited", "Salió de pantalla completa (muro)"),
            new("floating-created", "Ventana flotante creada"),
            new("floating-moved", "Ventana flotante movida"),
            new("floating-assigned", "Cámara asignada a flotante"),
            new("floating-fullscreen", "Flotante a pantalla completa"),
            new("floating-deleted", "Ventana flotante eliminada"),
            new("layout-saved", "Layout guardado"),
            new("layout-deleted", "Layout eliminado"),
            new("layout-applied", "Layout aplicado"),
        ]),
        new("anpr", "Patentes (ANPR)",
        [
            new("source-enabled", "Fuente de patentes activada"),
            new("source-disabled", "Fuente de patentes desactivada"),
            new("event-deleted", "Reconocimiento eliminado"),
            new("search", "Búsqueda en el historial"),
        ]),
        new("alarms", "Paneles de alarma",
        [
            new("panel-created", "Panel agregado"),
            new("panel-updated", "Panel modificado"),
            new("panel-deleted", "Panel eliminado"),
            new("panel-probed", "Prueba de conexión con panel"),
            new("receiver-devices-listed", "Equipos de la receptora consultados"),
            new("receiver-device-added", "Equipo agregado en la receptora"),
            new("receiver-device-removed", "Equipo quitado de la receptora"),
            new("receiver-credential-viewed", "Credencial de la receptora consultada"),
            new("panel-refreshed", "Estado del panel actualizado a pedido"),
            new("area-armed", "Área armada"),
            new("area-disarmed", "Área desarmada"),
            new("alarm-cleared", "Alarma borrada/silenciada"),
            new("zone-bypassed", "Zona anulada (bypass)"),
            new("zone-restored", "Zona restituida"),
            new("alarm-received", "Alarma recibida del panel"),
            new("panel-offline", "Panel sin conexión"),
            new("panel-online", "Panel recuperó conexión"),
            new("arc-started", "Receptor de alarmas (SIA DC-09) iniciado"),
            new("arc-rejected", "Reporte SIA DC-09 rechazado"),
            new("search", "Consulta del historial de eventos"),
        ]),
        new("access", "Control de acceso",
        [
            new("device-created", "Equipo agregado"),
            new("device-updated", "Equipo modificado"),
            new("device-deleted", "Equipo eliminado"),
            new("device-probed", "Prueba de conexión con equipo"),
            new("device-revalidated", "Equipo revalidado"),
            new("device-offline", "Equipo sin conexión"),
            new("device-online", "Equipo recuperó conexión"),
            new("discovery-scan", "Búsqueda de equipos en la red"),
            new("door-updated", "Puerta modificada"),
            new("door-opened", "Puerta abierta a distancia"),
            new("door-closed", "Puerta cerrada a distancia"),
            new("door-remain-open", "Puerta dejada abierta"),
            new("door-remain-locked", "Puerta bloqueada"),
            new("schedule-created", "Horario creado"),
            new("schedule-updated", "Horario modificado"),
            new("schedule-deleted", "Horario eliminado"),
            new("level-created", "Nivel de acceso creado"),
            new("level-updated", "Nivel de acceso modificado"),
            new("level-deleted", "Nivel de acceso eliminado"),
            new("level-assigned", "Personas de un nivel de acceso cambiadas"),
            new("person-created", "Persona agregada al padrón"),
            new("person-updated", "Persona modificada"),
            new("person-deleted", "Persona eliminada del padrón"),
            new("person-synced", "Persona reescrita en los equipos"),
            new("person-removed-from-device", "Persona quitada de un equipo"),
            new("sync-requested", "Escritura de lo pendiente"),
            new("sync-forced", "Reenvío forzado del padrón"),
            new("webcontrol-downloaded", "Instalador del complemento descargado"),
            new("search", "Consulta del historial de accesos"),
        ]),
        new("speakers", "Parlantes IP",
        [
            new("speaker-created", "Parlante agregado"),
            new("speaker-updated", "Parlante modificado"),
            new("speaker-deleted", "Parlante eliminado"),
            new("speaker-probed", "Prueba de conexión con parlante"),
            new("play", "Reproducción en parlante"),
            new("play-failed", "Reproducción rechazada por el parlante"),
            new("stop", "Reproducción detenida"),
            new("talk-started", "Voz en vivo iniciada"),
            new("talk-stopped", "Voz en vivo terminada"),
            new("talk-rejected", "Voz en vivo rechazada"),
            new("volume-changed", "Volumen cambiado"),
            new("library-uploaded", "Audio subido a la biblioteca del parlante"),
            new("library-deleted", "Audio borrado de la biblioteca del parlante"),
            new("library-renamed", "Audio renombrado en la biblioteca del parlante"),
            new("tts-created", "Audio de texto a voz creado"),
            new("speaker-offline", "Parlante sin conexión"),
            new("speaker-online", "Parlante recuperó conexión"),
        ]),
        new("intercom", "Citofonía",
        [
            new("intercom-created", "Frente de citofonía agregado"),
            new("intercom-updated", "Frente de citofonía modificado"),
            new("intercom-deleted", "Frente de citofonía eliminado"),
            new("intercom-probed", "Prueba de conexión con frente de citofonía"),
            new("call-center-configured", "Botón del frente configurado para llamar a la central"),
            new("video-optimized", "Video del frente ajustado (cuadro completo por segundo)"),
            new("call-ringing", "Llamada de citofonía recibida"),
            new("call-answered", "Llamada de citofonía contestada"),
            new("call-rejected", "Llamada de citofonía rechazada"),
            new("call-ended", "Llamada de citofonía terminada"),
            new("call-missed", "Llamada de citofonía no contestada"),
            new("call-command-failed", "Orden de llamada rechazada por el frente"),
            new("door-opened", "Puerta abierta desde citofonía"),
            new("door-open-failed", "Apertura de puerta fallida"),
            new("talk-started", "Conversación con el frente iniciada"),
            new("talk-stopped", "Conversación con el frente terminada"),
            new("talk-rejected", "Conversación con el frente rechazada"),
            new("history-viewed", "Consulta del historial de llamadas"),
            new("intercom-offline", "Frente de citofonía sin conexión"),
            new("intercom-online", "Frente de citofonía recuperó conexión"),
        ]),
        new("workflows", "Automatizaciones",
        [
            new("workflow-created", "Automatización creada"),
            new("workflow-updated", "Automatización modificada"),
            new("workflow-deleted", "Automatización eliminada"),
            new("workflow-duplicated", "Automatización duplicada"),
            new("workflow-tested", "Automatización probada a mano"),
            new("workflow-executed", "Automatización ejecutada"),
            new("workflow-failed", "Automatización con acciones fallidas"),
            new("workflow-webhook", "Automatización disparada por llamada externa"),
            new("workflow-webhook-rejected", "Llamada externa rechazada (clave inválida)"),
            new("alert-acknowledged", "Alerta confirmada por un operador"),
            new("smtp-updated", "Correo saliente configurado"),
            new("smtp-tested", "Correo de prueba enviado"),
            new("audio-uploaded", "Sonido de parlante subido"),
            new("audio-deleted", "Sonido de parlante eliminado"),
            new("search", "Consulta del historial de ejecuciones"),
        ]),
        new("license", "Licenciamiento",
        [
            new("license-activated", "Licencia activada en línea"),
            new("license-imported", "Archivo de licencia importado"),
            new("license-request-generated", "Solicitud de activación sin conexión generada"),
            new("license-refresh-requested", "Revalidación en línea solicitada"),
            new("license-validated", "Licencia revalidada en línea"),
            new("license-validation-failed", "Licencia invalidada por el servidor de licencias"),
            new("license-deactivated", "Licencia desactivada en este equipo"),
            new("license-active", "Licencia vigente"),
            new("license-trial", "Período de prueba en curso"),
            new("license-grace", "Licencia en período de gracia"),
            new("license-restricted", "Sistema en modo restringido por licencia"),
            new("license-unlicensed", "Sistema sin licencia"),
            new("license-warning", "Aviso de licencia por vencer"),
            new("license-denied", "Operación rechazada por licencia (módulo o cupo)"),
            new("license-channels-restored", "Canales habilitados al haber cupo en la licencia"),
        ]),
        new("system", "Sistema",
        [
            new("server-started", "Servidor iniciado"),
            new("server-stopped", "Servidor detenido"),
            new("audit-purged", "Bitácora purgada por retención"),
            new("audit-exported", "Bitácora exportada a CSV"),
            new("service-started", "Servicio iniciado"),
            new("service-stopped", "Servicio detenido"),
            new("service-restarted", "Servicio reiniciado"),
            new("service-failed", "Servicio caído (detectado por el supervisor)"),
            new("service-autorestart-changed", "Auto-reinicio de servicio cambiado"),
            new("server-restart-requested", "Reinicio completo del servidor solicitado"),
        ]),
    ];

    /// <summary>Acciones que el cliente de escritorio puede reportar, y a qué
    /// categoría/acción de la bitácora se traducen. Todo lo demás se rechaza:
    /// un cliente no puede inventar eventos de otras categorías.</summary>
    public static readonly IReadOnlyDictionary<string, (string Category, string Action, string Detail)> ClientActions =
        new Dictionary<string, (string, string, string)>(StringComparer.OrdinalIgnoreCase)
        {
            ["live-snapshot"] = ("live", "snapshot-client", "Guardó una captura de video en vivo"),
            ["live-clip-start"] = ("live", "clip-started", "Inició una grabación local de video en vivo"),
            ["live-clip-saved"] = ("live", "clip-saved", "Guardó una grabación local de video en vivo"),
            ["playback-snapshot"] = ("playback", "snapshot-saved", "Guardó una captura durante la reproducción"),
            ["playback-clip-saved"] = ("playback", "clip-saved", "Guardó una cápsula durante la reproducción"),
            ["playback-export-saved"] = ("playback", "export-saved", "Guardó una exportación de grabación"),
            ["playback-export-cancelled"] = ("playback", "export-cancelled", "Canceló una exportación de grabación"),
            ["playback-export-failed"] = ("playback", "export-failed", "Falló una exportación de grabación"),
        };
}
